name: My first workflow
on: push

jobs:
  my_first_job:
    name: Compile job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          scripts/compile.sh
  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
    steps:
      - name: Greeting from second job
        run: |
          echo "Hello, world from 2nd job"